version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    container_name: nextjs-container